//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TonerCartridgeApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<int> AccessLevel { get; set; }
    }
}
